#ifndef JSON_CONFIG_TYPE_FILE_SEQUENCE_IN_A_CYCLE_PRIVATE_H
#define JSON_CONFIG_TYPE_FILE_SEQUENCE_IN_A_CYCLE_PRIVATE_H

int
json_config_type_file_seq_cycle_init();

int
json_config_type_file_seq_cycle_uninit();

#endif
