[general]
netcard = "eth0"
linger = 1
total_link = 1
port_map = 1
ip_count = 1
start_ip = "192.168.0.140"
server_ip = "192.168.0.1"
server_port = 80
start_port = 15000
end_port = 65000
duration = "0:23:0:10"
recv_timeout = 10
connect_timeout = 10
add_check = 1
timer_thread_num = 32
proto = "tcp"
device = "client"
open_hub = 1
hub_interval = 3

[test_interface]
input_path = "config/proj_test/json_input.txt"
input_check = "config/proj_test/json_check.txt"
