
all:
	#pushd libtoml-master;cmake -G "Unix Makefiles" .; popd;
	#make -C ./libtoml-master/	
	#mv ./libtoml-master/libtoml.* ../comm_lib
	cp ./lib64/libtoml.so $(CommLib)
	cp ./libtoml-master/*.h $(CommInc)


clean:
#	make -C ./libtoml-master/ clean
#	rm -rf ../comm_lib/libtoml.*

