
all:
	#pushd libtoml-master;cmake -G "Unix Makefiles" .; popd;
	#make -C ./libtoml-master/	
	#mv ./libtoml-master/libtoml.* ../comm_lib
	cp ./*.so* $(CommLib)


clean:
#	make -C ./libtoml-master/ clean
#	rm -rf ../comm_lib/libtoml.*

