[genernal]
dev_type = "client"
total_link = 1
ip_count = 1
port_map = 1
duration_time = "0:1:1:10"
[thread]
hub_thread_num = 1
recv_thread_num = 1
send_thread_num = 1
timer_thread_num = 1
dispose_thread_num = 1
push_data_thread_num = 1
recv_check_thread_num = 1
[private]
start_ip = "192.168.0.103"
start_port = 19_999
end_port = 20_000
server_ip = "192.168.0.103"
server_port = 15_000
ml_data = 10
proj_num = 10

